export const TechTeamList = [
  {
    id: 1,
    name: "Sai Aneesh",
    image: "https://i.imgur.com/B4bRirZ.jpeg",
    year: "II Year",
    branch: "CSE AIML",
    linkedin: "www.linkedin.com/in/saianeeshg90",
    instagram: "https://www.instagram.com/teabagme0/",
  },
  {
    id: 2,
    name: "G. RishiKesh",
    image: "https://i.imgur.com/W9SpEjM.jpeg",
    year: "III Year",
    branch: "CSE",
    linkedin: "https://www.linkedin.com/in/rishikesh-gunda-051bb9255",
  },
  {
    id: 3,
    name: "Vardhan Reddy",
    image: "https://i.imgur.com/VeMoGpR.jpeg",
    year: "III Year",
    branch: "CSE",
    linkedin:
      "https://www.linkedin.com/in/gurrampati-venkat-harsha-vardhan-reddy-59b88b259",
    instagram: "https://www.instagram.com/gvhvardhan",
  },
  {
    id: 4,
    name: "Omer Abdullah",
    image: "https://i.imgur.com/x1QPfAB.jpeg",
    year: "II Year",
    branch: "CSE AIML",
    linkedin: "https://www.linkedin.com/in/0m3r",
    instagram: "https://www.instagram.com/0m3r.exe",
  },

  {
    id: 5,
    name: "Dharani",
    image: "https://i.imgur.com/CwBzSpX.jpeg",
    year: "III Year",
    branch: "CSE DS",
    linkedin: "https://www.linkedin.com/in/dharani-lakkireddy",
    instagram: "https://www.instagram.com/dharani_3087/",
  },
  {
    id: 6,
    name: "Sai Srujan",
    image: "https://i.imgur.com/hlnCli5.jpeg",
    year: "I Year",
    branch: "IT",
    linkedin: "https://www.linkedin.com/in/saisrujanpunati",
    instagram:
      "https://www.instagram.com/__saisrujan__?igsh=MXhldmZkNnFpbGs0cw==",
  },
  {
    id: 7,
    name: "Jonnada Mahesh",
    image: "https://i.imgur.com/0IBUXWs.jpeg",
    year: "II Year",
    branch: "CSE DS",
    linkedin: "https://www.linkedin.com/in/jonnada-mahesh-a72b0328a",
    instagram: "https://www.instagram.com/jonnada_mahesh_/",
  },
];

export const PRORTeamList = [
  {
    id: 1,
    name: "Yuvraj",
    image: "https://i.imgur.com/P24q368.jpeg",
    year: "I Year",
    branch: "CSE",
    instagram: "https://www.instagram.com/yuvies.45/",
  },
  {
    id: 2,
    name: "N Prashanth Goud",
    image: "https://i.imgur.com/vkvorQg.jpeg",
    year: "III Year",
    branch: "CSE",
    linkedin: "https://www.linkedin.com/in/prashanth-goud-7b8864294",
    instagram: "https://www.instagram.com/prashanthh.006",
  },
  {
    id: 3,
    name: "Samiksha Salunke",
    image: "https://i.imgur.com/QlZgpZh.jpeg",
    year: "III Year",
    branch: "CSE",
    linkedin: "https://www.linkedin.com/in/samiksha-salunke-6b0b66259/",
    instagram: "https://www.instagram.com/_samiksha.146/",
  },
  {
    id: 4,
    name: "Sanobar Unissa",
    image: "https://i.imgur.com/T64j6Z3.jpeg",
    year: "II Year",
    branch: "CSE DS",
    linkedin: "https://www.linkedin.com/in/sanobar-unissa-71a0092a6/",
    instagram: "https://www.instagram.com/sanobar_unissa/",
  },
  {
    id: 5,
    name: "Athikah",
    image: "https://i.imgur.com/Vjlx0Eg.jpeg",
    year: "I Year",
    branch: "IT",
    linkedin: "https://www.linkedin.com/in/athikah-azeem-2287b2328",
    instagram: "https://www.instagram.com/athikah_aa/",
  },
  {
    id: 6,
    name: "D. Saathwika",
    image: "https://i.imgur.com/8sXLb2c.jpeg",
    year: "I Year",
    branch: "CSE",
    linkedin: "https://www.linkedin.com/in/saathwika-doma-a97a90313",
    instagram:
      "https://www.instagram.com/siri_saathwika?igsh=MWhhdTR3ejJseHZzNw",
  },
  {
    id: 7,
    name: "P. Naga Bhavagnya",
    image: "https://i.imgur.com/aRVyCXT.png",
    year: "II Year",
    branch: "IT",
    linkedin: "https://www.linkedin.com/in/bhavagnya-p-384858297",
    instagram: "https://www.instagram.com/bhavi1_7/",
  },
];

export const DesignTeamList = [
  {
    id: 1,
    name: "Ujasvi Singh",
    image: "https://i.imgur.com/jfavbTG.jpeg",
    year: "III Year",
    branch: "CSE",
    linkedin: "https://www.linkedin.com/in/thakur-ujasvi-singh-19811a25a",
    instagram: "https://www.instagram.com/ujasvi.thakur/",
  },
  {
    id: 2,
    name: "Ananditha G",
    image: "https://i.imgur.com/MnJbBY4.png",
    year: "II Year",
    branch: "CSE DS",
    linkedin: "https://www.linkedin.com/in/ananditha-gangadharpalli-7666a6296",
    instagram: "https://www.instagram.com/anandi._tha/",
  },
  {
    id: 3,
    name: "Hema Sathvika",
    image: "https://i.imgur.com/1wu35Vr.jpeg",
    year: "I Year",
    branch: "CSE AIML",
    linkedin: "https://www.linkedin.com/in/nadapana-hema-sathvika-9b76a0300",
    instagram: "https://www.instagram.com/seekingserenity_ss",
  },
  {
    id: 4,
    name: "Jagruthi Gadila",
    image: "https://i.imgur.com/xjJ0711.jpeg",
    year: "II Year",
    branch: "AI",
    linkedin: "https://www.linkedin.com/in/jagruthi-gadila-1065a82b8/",
    instagram: "https://www.instagram.com/jagruthii_reddy_/",
  },
];

export const NonTechTeamList = [
  {
    id: 1,
    name: "Koustubh Joshi",
    image: "https://i.imgur.com/4IuQHs4.jpeg",
    year: "II Year",
    branch: "ECE",
    instagram: "https://www.instagram.com/koustubh_joshi_1729/",
  },
  {
    id: 2,
    name: "Saira Khan",
    image: "https://i.imgur.com/2Ec17yi.jpeg",
    year: "III Year",
    branch: "CSE",
    linkedin: "https://www.linkedin.com/in/saira-khan-6a7b66259/",
    instagram: "https://www.instagram.com/sairak25011/",
  },
  {
    id: 3,
    name: "John Abraham",
    image: "https://i.imgur.com/gA9EosH.jpeg",
    year: "III Year",
    branch: "CSE AIML",
    linkedin: "https://www.linkedin.com/in/john-abraham-charlapally",
    instagram: "https://www.instagram.com/thefantabulous7/",
  },
  {
    id: 4,
    name: "Kodur Sidheshwar",
    image: "https://i.imgur.com/RNQllHw.jpeg",
    year: "II Year",
    branch: "CSE DS",
    linkedin: "https://www.linkedin.com/in/kodur-sidheshwar-8255b42b8",
    instagram:
      "https://www.instagram.com/sidheshwar0205?igsh=MXA4dWE3c2h2bGN5bw==",
  },
  {
    id: 5,
    name: "Aila Vishnu Vardhan",
    image: "https://i.imgur.com/ituBDxN.jpeg",
    year: "II Year",
    branch: "CSE DS",
    linkedin: "https://www.linkedin.com/in/ailavishnuvardhan/",
    instagram: "https://www.instagram.com/vishnuuu_._/",
  },
  {
    id: 6,
    name: "Suchismita Jena",
    image: "https://i.imgur.com/XwnEfSX.jpeg",
    year: "II Year",
    branch: "CSE DS",
    linkedin: "https://www.linkedin.com/in/suchismita-jena-36089a28b/",
    instagram: "https://www.instagram.com/suchiz__/",
  },
  {
    id: 7,
    name: "Kevin Jonathan",
    image: "https://i.imgur.com/k9AHOVi.jpeg",
    year: "III Year",
    branch: "CSE",
    linkedin: "https://www.linkedin.com/in/kevin-jonathan-433a75259/",
    instagram: "https://www.instagram.com/kevinjonathan07/",
  },
  {
    id: 8,
    name: "Prashanth Pendem",
    image: "https://i.imgur.com/TgQTCDR.png",
    year: "II Year",
    branch: "CSE",
    instagram: "https://www.instagram.com/prashanth_pendem_49/",
    linkedin: "https://www.linkedin.com/in/pendem-prashanth-223aab2b9/",
  },
  {
    id: 9,
    name: "Vedant Idlgave",
    image: "https://i.imgur.com/NxqYNwS.jpeg",
    year: "I Year",
    branch: "CSE DS",
    linkedin: "https://www.linkedin.com/in/vedant-idlgave-70040b331/",
    instagram: "https://www.instagram.com/vedant_15_200/",
  },
  {
    id: 10,
    name: "V Preeti",
    image: "https://i.imgur.com/7YX8WGF.jpeg",
    year: "II Year",
    branch: "AI",
    linkedin: "https://www.linkedin.com/in/preethi-varri-163028322/",
    instagram: "https://www.instagram.com/preethi__1223/",
  },
  {
    id: 11,
    name: "Saiteja Veerabomma",
    image: "https://i.imgur.com/XdzQ3Jb.jpeg",
    year: "II Year",
    branch: "CSE DS",
    linkedin: "https://www.linkedin.com/in/saiteja-veerabomma-0805b22b8",
    instagram: "https://www.instagram.com/_vsaiteja_/",
  },
];

export const TeamContentList = {
  technical: {
    name: "Kaushik Katikala",
    title: "Meet the Visionaries Powering Our Tech",
    description:
      "Our technical team drives the future with expertise, passion, and cutting-edge technology.",
    leadImage: "https://i.imgur.com/gYlmaqt.png",
    position: "Technical",
    team: TechTeamList,
  },
  design: {
    name: "Hima Bala",
    title: "Meet the Creatives Crafting Our Vision",
    description:
      "Our design team brings ideas to life with stunning visuals, intuitive interfaces, and seamless user experiences.",
    leadImage: "https://i.imgur.com/WULnIKF.jpeg",
    position: "Design",
    team: DesignTeamList,
  },
  "non-technical": {
    name: "Harshith Pilli",
    title: "Meet the Leaders Steering Our Growth",
    description:
      "They empower the community to achieve greatness through effective management and leadership.",
    leadImage: "https://i.imgur.com/3umE9SL.jpeg",
    position: "Non-Technical",
    team: NonTechTeamList,
  },
  "pr-or": {
    name: "Abdus Samee",
    title: "Meet the Voices Amplifying Our Reach",
    description:
      "Our PR-OR team is the voice of DSS, spreading awareness, building connections, and engaging the community. ",
    leadImage: "https://i.imgur.com/wBfegLG.jpeg",
    position: "PR-OR",
    team: PRORTeamList,
  },
};

export const CoreTeamList = [
  {
    id: 1,
    name: "Kaushik Katikala",
    position: "Technical Lead",
    image: "https://i.imgur.com/gYlmaqt.png",
    href: "/about/technical",
    linkedin: "https://www.linkedin.com/in/kaushik-katikala/",
    instagram: "https://www.instagram.com/_kaushik_1706/",
  },
  {
    id: 2,
    name: "Harshith Pilli",
    position: "Non-Technical Lead",
    image: "https://i.imgur.com/3umE9SL.jpeg",
    href: "/about/non-technical",
    linkedin: "https://www.linkedin.com/in/harshith-pilli-73012125a/",
    instagram: "https://www.instagram.com/harshithpilli.02/",
  },
  {
    id: 3,
    name: "Abdus Samee",
    position: "PR-OR Lead",
    image: "https://i.imgur.com/wBfegLG.jpeg",
    href: "/about/pr-or",
    linkedin: "https://www.linkedin.com/in/shaik-mohammed-abdus-samee/",
    instagram: "https://www.instagram.com/abdus_samee_007/",
  },
  {
    id: 4,
    name: "Hima Bala",
    position: "Design Lead",
    image: "https://i.imgur.com/WULnIKF.jpeg",
    href: "/about/design",
    linkedin: "https://www.linkedin.com/in/himabala-bandaru-176508281/",
    instagram: "https://www.instagram.com/himabala_/",
  },
];
